apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
type: Opaque
stringData: # Or use 'data' and base64 encode values
  connection-string: postgresql://user:password@postgres-db:5432/database_name # Replace with your actual database credentials.  Do NOT hardcode these! Use a secrets management solution.
