apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service
      targetPort: 80 # Port the container listens on
  type: LoadBalancer # Or ClusterIP if internal
